/**
 * @file Corpus.h
 * @brief The statistics of the local trance MIDI corpus (PLAN 6.6, stage A) and the constrained sampler that draws lines
 *        from them.
 *
 * **The tables** (CorpusTables.cpp, generated by Tools/corpus/build_corpus.py from the royalty-free EMP packs of the
 * VORTEX bundle: 500 melodies, 100 piano lines, 108 acid lines, 200 basslines): per role the successions of scale steps of
 * order 0, 1 and 2 (a step is a note's diatonic place above the minor tonic, -7 .. +14), the onsets on the 32 sixteenths
 * of two bars given the step before, the note lengths, the 303's accents and slides per sixteenth. Counts only.
 *
 * **The model** is a variable-order predictor over the steps (Begleiter, El-Yaniv and Yona 2004): order 2 where the corpus
 * has seen the context, backed off to order 1 and 0 by Witten-Bell interpolation.
 *
 * **The sampler** (Pachet and Roy, "Markov Constraints", 2011): a line of n notes is drawn exactly under per-position
 * constraints -- a set of allowed steps at every position (the scale's range, the chord's tones on strong sixteenths, the
 * phrase's end) -- by a backward pass that sums, for every position and state, the weight of all completions that satisfy
 * the constraints, and a forward pass that draws in proportion to it. Nothing is drawn that breaks a constraint, and
 * nothing that keeps them is less likely than the model says. A shaping factor per transition (the contour: a leap at the
 * phrase's start, a walk down to its end) multiplies the model's weights.
 */
#pragma once
#include "parh/Dsp.h"
#include <array>
#include <cstdint>
#include <functional>
#include <vector>

namespace parh {

constexpr int kCorpusStepMin = -7;      ///< the lowest scale step (an octave under the tonic)
constexpr int kCorpusAlpha = 22;        ///< steps -7 .. +14
constexpr int kCorpusRoleCount = 4;        ///< lead, piano, acid, bass

/** @brief The roles the corpus has counts for. */
enum class CorpusRoleId : int { Lead = 0, Piano, Acid, Bass };

/** @brief One order-2 count. */
struct CorpusTriple { uint8_t a, b, c; uint16_t n; };

/** @brief The counts of one role. */
struct CorpusRole {
    const uint16_t* t0;                                  ///< [kCorpusAlpha]
    const uint16_t (*t1)[kCorpusAlpha];                  ///< [kCorpusAlpha][kCorpusAlpha]
    const CorpusTriple* t2;                              ///< sparse order-2 counts, sorted by (a, b, c)
    int t2Count;
    const uint16_t (*onset)[2];                          ///< [64][2]: step (0..31) + 32 if the step before had an onset: (no, yes)
    const uint16_t* length;                              ///< [17]: note lengths in sixteenths (16: longer)
    const uint16_t (*accent)[2];                         ///< [16][2]
    const uint16_t (*slide)[2];                          ///< [16][2]
};
extern const CorpusRole kCorpusRoles[kCorpusRoleCount];

/** @brief The variable-order model of one role: P(next step | two steps before). */
class StepModel {
public:
    explicit StepModel(CorpusRoleId role);
    /** @brief The probability of step @p c after @p a, @p b (indices 0 .. kCorpusAlpha-1; @p a < 0: no second context). */
    double p(int a, int b, int c) const;
    /** @brief The chance of an onset on sixteenth @p step (0 .. 31) given whether the step before had one. */
    double onset(int step, bool prev) const;
    /** @brief The chance of an accent and of a slide on sixteenth @p step (0 .. 15). */
    double accent(int step) const;
    double slide(int step) const;
private:
    const CorpusRole& r_;
    std::vector<float> p1_;                    ///< order 1 with Witten-Bell back-off to order 0, [a][c]
    std::vector<float> p2_;                    ///< order 2 interpolated, [a][b][c]
};

/** @brief The model of @p role, built once (thread-safe). */
const StepModel& corpusModel(CorpusRoleId role);

/**
 * @brief Draws a line of @p n steps exactly under constraints (Pachet and Roy 2011) from @p model.
 * @param allowed  allowed[i][s]: whether step index s may stand at position i
 * @param shape    an extra weight on the transition (i, a, b, c) -> c at position i (1: none); may be empty
 * @param r        the stream
 * @param out      receives the step indices (0 .. kCorpusAlpha-1)
 * @return false if no line satisfies the constraints
 */
bool sampleConstrained(const StepModel& model, int n, const std::vector<std::array<bool, kCorpusAlpha>>& allowed,
                       const std::function<double(int, int, int, int)>& shape, Rng& r, std::vector<int>& out);

} // namespace parh
