"""Writes Core/src/PresetBankData.inl from Tools/presets/bank_spec.py (Phase 5b).

    python Tools/presets/gen_bank.py

Checks what the C++ side cannot see at a glance: eight adjectives, sixteen groups of eight nouns in every bank, every
preset name unique within its bank, every style a tuple of five. Where Core/src/PresetTrims.inl is missing it writes one
of zeros (the self test measures the trims: parh_selftest testPresetBank with PARH_BANK_TRIMS=<that file>).

@note After Phosphene `Tools/presets/gen_bank.py` at 76f7100 (29.09.2026); the lists, the roles and the banks are new.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import bank_spec as S  # noqa: E402

CORE = os.path.join(HERE, "..", "..", "Core", "src")
OUT = os.path.join(CORE, "PresetBankData.inl")
TRIMS = os.path.join(CORE, "PresetTrims.inl")


def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def knob(k):
    key, lo, hi, axis = k
    ax = "'" + axis + "'"
    if isinstance(lo, str):
        assert lo.startswith("list:"), (key, lo)
        return f"{{ {cstr(key)}, 0.0f, 0.0f, {ax}, {cstr(lo)} }}"
    return f"{{ {cstr(key)}, {float(lo)!r}f, {float(hi)!r}f, {ax}, nullptr }}"


def group_code(g):
    assert len(g["nouns"]) == 8, g["name"]
    assert len(g["style"]) == 5, g["name"]
    roles = 0
    for r in g["roles"] or []:
        roles |= 1 << r
    knobs = ", ".join(knob(k) for k in g["knobs"])
    mods = ", ".join(f"{{ {float(ch)!r}f, {{ {', '.join(knob(k) for k in ks)} }} }}" for ch, ks in g["mods"])
    styles = ", ".join(f"{float(x)!r}f" for x in g["style"])
    return (f"        {{ {cstr(g['name'])}, {{ {', '.join(cstr(n) for n in g['nouns'])} }}, {{ {styles} }}, {roles}u,\n"
            f"          {{ {knobs} }},\n          {{ {mods} }} }}")


def bank_code(b):
    assert len(b["adj"]) == 8, b["label"]
    assert len(b["groups"]) == 16, (b["label"], len(b["groups"]))
    names = set()
    for g in b["groups"]:
        for a in b["adj"]:
            for n in g["nouns"]:
                nm = a + " " + n
                assert nm not in names, (b["label"], nm)
                names.add(nm)
    parts = ",\n".join(group_code(g) for g in b["groups"])
    return (f"    {{ {cstr(b['label'])}, Module::{b['module']}, {b['instance']}, {{ {', '.join(cstr(a) for a in b['adj'])} }}, {{\n"
            + parts + "\n    } }")


def main():
    assert len(S.BANKS) == 18, len(S.BANKS)
    text = ("// Generated by Tools/presets/gen_bank.py from Tools/presets/bank_spec.py -- do not edit; edit the spec.\n"
            "// Included by PresetBank.cpp inside namespace parh::bank.\n"
            "const std::vector<Bank>& banks()\n{\n    static const std::vector<Bank> k = {\n"
            + ",\n".join(bank_code(b) for b in S.BANKS) + "\n    };\n    return k;\n}\n")
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"wrote {OUT}: {len(S.BANKS)} banks x 16 groups x 64 presets = {len(S.BANKS) * 1024}")
    if not os.path.exists(TRIMS):
        with open(TRIMS, "w", encoding="utf-8", newline="\n") as f:
            f.write("// Generated by parh_selftest testPresetBank with PARH_BANK_TRIMS=<this file> (Tests/selftest.cpp).\n"
                    "// Each preset's level correction in tenths of a dB, 18 banks of 1024 (Presets.h's order). Zeros: not measured yet.\n"
                    "static const short kPresetTrimTenths[18][1024] = {};\n")
        print(f"wrote {TRIMS} (zeros)")


if __name__ == "__main__":
    main()
